/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.RentCar;

import javax.swing.JOptionPane;

/**
 *
 * @author María Fernanda Murillo Alfaro
 * @author Karla Vanessa Ballestero Castro
 * @date 29/11/2017
 *
 */
public class FrmCRUDOffice extends javax.swing.JFrame {

    /**
     * Creates new form FrmCRUDOffice
     */
    public FrmCRUDOffice() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    //Method to close session
    private void LogOut() {
        JOptionPane.showMessageDialog(null, "Finalized session");
        FrmLogin out = new FrmLogin();
        out.setVisible(true);
        dispose();
    }
     
    //Method to go admin menu
    private void goMenu(){
        FrmMenuAdmin menu = new FrmMenuAdmin();
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        dispose();
    }
    
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblWallpaper = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblWallpaper1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblWallpaper2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblWallpaper3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mbarFile = new javax.swing.JMenu();
        mniMenu = new javax.swing.JMenuItem();
        mniLogOut = new javax.swing.JMenuItem();
        mbarExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/Wallpaper_Second.jpg"))); // NOI18N
        jPanel1.add(lblWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 550));

        jTabbedPane1.addTab("Register", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWallpaper1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/Wallpaper_Second.jpg"))); // NOI18N
        jPanel2.add(lblWallpaper1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 550));

        jTabbedPane1.addTab("Update", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWallpaper2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/Wallpaper_Second.jpg"))); // NOI18N
        jPanel3.add(lblWallpaper2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 550));

        jTabbedPane1.addTab("Charge", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWallpaper3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/Wallpaper_Second.jpg"))); // NOI18N
        jPanel4.add(lblWallpaper3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 550));

        jTabbedPane1.addTab("Delete", jPanel4);

        mbarFile.setText("File");
        mbarFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbarFileActionPerformed(evt);
            }
        });

        mniMenu.setText("Menu");
        mniMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniMenuActionPerformed(evt);
            }
        });
        mbarFile.add(mniMenu);

        mniLogOut.setText("Log Out");
        mniLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLogOutActionPerformed(evt);
            }
        });
        mbarFile.add(mniLogOut);

        jMenuBar1.add(mbarFile);

        mbarExit.setText("Exit");
        mbarExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbarExitActionPerformed(evt);
            }
        });
        jMenuBar1.add(mbarExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLogOutActionPerformed
        LogOut();
    }//GEN-LAST:event_mniLogOutActionPerformed

    private void mbarExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbarExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mbarExitActionPerformed

    private void mbarFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbarFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbarFileActionPerformed

    private void mniMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMenuActionPerformed
        goMenu();
    }//GEN-LAST:event_mniMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCRUDOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCRUDOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCRUDOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCRUDOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCRUDOffice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblWallpaper;
    private javax.swing.JLabel lblWallpaper1;
    private javax.swing.JLabel lblWallpaper2;
    private javax.swing.JLabel lblWallpaper3;
    private javax.swing.JMenu mbarExit;
    private javax.swing.JMenu mbarFile;
    private javax.swing.JMenuItem mniLogOut;
    private javax.swing.JMenuItem mniMenu;
    // End of variables declaration//GEN-END:variables
}
