/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.RentCar;

import BO.RentCar.CarBO;
import Logic.RentCar.Car;
import java.awt.Image;
import java.io.File;
import java.util.LinkedList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author María Fernanda Murillo Alfaro
 * @author Karla Vanessa Ballestero Castro
 * @date 28/11/2017
 *
 */
public class FrmCRUDCar extends javax.swing.JFrame {
    private LinkedList<Car> carList;
    private File file;
    private String photo;
    /**
     * Creates new form FrmRegisterCar
     */
    public FrmCRUDCar() {
        initComponents();
        this.setLocationRelativeTo(null);
        carList = new LinkedList<>();
        
    }
    
    public FrmCRUDCar(LinkedList<Car> carList) {
        this.carList = carList;
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */



    //Method to register
    private void registerNewCar() {
        try {
            CarBO cbo = new CarBO();
            Car c = new Car();
            c.setId_car(txtIDCar.getText());
            c.setBrand_car((String)cbxBrand.getSelectedItem());
            c.setModel_car((String)cbxModel.getSelectedItem());
            c.setStyle_car((String)cbxStyle.getSelectedItem());
            c.setTransmission_car((String)cbxTransmission.getSelectedItem());
            c.setYear_car((String)cbxYear.getSelectedItem());
            c.setAvailable_car((String)cbxAvailable.getSelectedItem());
            c.setPhoto_car(photo);
            c.setPrice_car(Integer.parseInt(txtPrice.getText()));

                if (cbo.register(c)) {
                    JOptionPane.showMessageDialog(null, "Registered");
                }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    
    //Method to close session
    private void LogOut() {
        JOptionPane.showMessageDialog(null, "Finalized session");
        FrmLogin out = new FrmLogin();
        out.setVisible(true);
        dispose();
    }  
    
    //Method to go admin menu
    private void goMenu(){
        FrmMenuAdmin menu = new FrmMenuAdmin();
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        dispose();
    }
    
    
        //Method for find a photo
    private void findPhoto() {
        int result;
        FrmPhoto frm = new FrmPhoto();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG and PNG", "jpg", "png");
        frm.jfchPhoto.setFileFilter(filter);
        result = frm.jfchPhoto.showOpenDialog(null);
        if (JFileChooser.APPROVE_OPTION == result) {
            file = frm.jfchPhoto.getSelectedFile();
            try {
                ImageIcon icon = new ImageIcon(file.toString());
                photo = file.toString();
                Icon picture = new ImageIcon(icon.getImage().getScaledInstance(lblPhoto.getWidth(), lblPhoto.getHeight(), Image.SCALE_DEFAULT));
                lblPhoto.setText("");
                lblPhoto.setIcon(picture);
            } catch (Exception ex) {
                System.out.println("Error opening the image" + ex);
            }
        }
    }

    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();
        lblIDCar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIDCar = new javax.swing.JTextField();
        cbxBrand = new javax.swing.JComboBox<>();
        cbxModel = new javax.swing.JComboBox<>();
        cbxStyle = new javax.swing.JComboBox<>();
        cbxTransmission = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        btnFindPhoto = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbxYear = new javax.swing.JComboBox<>();
        txtPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbxAvailable = new javax.swing.JComboBox<>();
        lblWallpaper = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnFind = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblWallpaper1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSee = new javax.swing.JButton();
        lblWallpaper2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mbarFile = new javax.swing.JMenu();
        mniMenuAdmin = new javax.swing.JMenuItem();
        mniLogOut = new javax.swing.JMenuItem();
        mbarExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegister.setBackground(new java.awt.Color(102, 102, 0));
        btnRegister.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 230, 70));

        lblIDCar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblIDCar.setForeground(new java.awt.Color(255, 255, 255));
        lblIDCar.setText("ID car:");
        jPanel1.add(lblIDCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Brand:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtIDCar.setBackground(new java.awt.Color(51, 51, 51));
        txtIDCar.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtIDCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 140, -1));

        cbxBrand.setBackground(new java.awt.Color(51, 51, 51));
        cbxBrand.setForeground(new java.awt.Color(255, 255, 255));
        cbxBrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------Select--------", "Nissan", "Toyota", "Hyunday" }));
        jPanel1.add(cbxBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 140, -1));

        cbxModel.setBackground(new java.awt.Color(51, 51, 51));
        cbxModel.setForeground(new java.awt.Color(255, 255, 255));
        cbxModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------Select--------", "Tucson 2018" }));
        jPanel1.add(cbxModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 140, -1));

        cbxStyle.setBackground(new java.awt.Color(51, 51, 51));
        cbxStyle.setForeground(new java.awt.Color(255, 255, 255));
        cbxStyle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------Select--------", "Automobile", "Pick up", "Microbus", "Sport" }));
        jPanel1.add(cbxStyle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 140, -1));

        cbxTransmission.setBackground(new java.awt.Color(51, 51, 51));
        cbxTransmission.setForeground(new java.awt.Color(255, 255, 255));
        cbxTransmission.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------Select--------", "Automatic", "Manual" }));
        jPanel1.add(cbxTransmission, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 150, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Model:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Style:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Transmission:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));
        jPanel1.add(lblPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 50, 190, 190));

        btnFindPhoto.setBackground(new java.awt.Color(102, 102, 0));
        btnFindPhoto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnFindPhoto.setForeground(new java.awt.Color(255, 255, 255));
        btnFindPhoto.setText("Find a photo");
        btnFindPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindPhotoActionPerformed(evt);
            }
        });
        jPanel1.add(btnFindPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 250, 180, 40));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Year:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Price:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));

        cbxYear.setBackground(new java.awt.Color(51, 51, 51));
        cbxYear.setForeground(new java.awt.Color(255, 255, 255));
        cbxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------Select--------", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018" }));
        jPanel1.add(cbxYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 150, -1));

        txtPrice.setBackground(new java.awt.Color(51, 51, 51));
        txtPrice.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 150, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Availalble:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        cbxAvailable.setBackground(new java.awt.Color(51, 51, 51));
        cbxAvailable.setForeground(new java.awt.Color(255, 255, 255));
        cbxAvailable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------Select--------", "Yes", "No" }));
        jPanel1.add(cbxAvailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 150, -1));

        lblWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/Wallpaper_Second.jpg"))); // NOI18N
        jPanel1.add(lblWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 600, 630));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/Wallpaper_Second.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, 610));

        jTabbedPane1.addTab("Register", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFind.setBackground(new java.awt.Color(102, 102, 0));
        btnFind.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnFind.setForeground(new java.awt.Color(255, 255, 255));
        btnFind.setText("Find");
        jPanel2.add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 100, 30));

        btnUpdate.setBackground(new java.awt.Color(102, 102, 0));
        btnUpdate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 100, -1));

        btnDelete.setBackground(new java.awt.Color(102, 102, 0));
        btnDelete.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 100, -1));

        lblWallpaper1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/Wallpaper_Second.jpg"))); // NOI18N
        jPanel2.add(lblWallpaper1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 630));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/Wallpaper_Second.jpg"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, 610));

        jTabbedPane1.addTab("Update", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 1160, 270));

        btnSee.setBackground(new java.awt.Color(102, 102, 0));
        btnSee.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSee.setForeground(new java.awt.Color(255, 255, 255));
        btnSee.setText("See");
        jPanel3.add(btnSee, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 140, 40));

        lblWallpaper2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/Wallpaper_Second.jpg"))); // NOI18N
        jPanel3.add(lblWallpaper2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 20, 740, 570));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/Wallpaper_Second.jpg"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, 600));

        jTabbedPane1.addTab("See all", jPanel3);

        mbarFile.setText("File");

        mniMenuAdmin.setText("Menu");
        mbarFile.add(mniMenuAdmin);

        mniLogOut.setText("Log Out");
        mniLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLogOutActionPerformed(evt);
            }
        });
        mbarFile.add(mniLogOut);

        jMenuBar1.add(mbarFile);

        mbarExit.setText("Exit");
        mbarExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbarExitActionPerformed(evt);
            }
        });
        jMenuBar1.add(mbarExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLogOutActionPerformed
        LogOut();
    }//GEN-LAST:event_mniLogOutActionPerformed

    private void mbarExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbarExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mbarExitActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        registerNewCar();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnFindPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindPhotoActionPerformed
        findPhoto();
    }//GEN-LAST:event_btnFindPhotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCRUDCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCRUDCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCRUDCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCRUDCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCRUDCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFindPhoto;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSee;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbxAvailable;
    private javax.swing.JComboBox<String> cbxBrand;
    private javax.swing.JComboBox<String> cbxModel;
    private javax.swing.JComboBox<String> cbxStyle;
    private javax.swing.JComboBox<String> cbxTransmission;
    private javax.swing.JComboBox<String> cbxYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblIDCar;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblWallpaper;
    private javax.swing.JLabel lblWallpaper1;
    private javax.swing.JLabel lblWallpaper2;
    private javax.swing.JMenu mbarExit;
    private javax.swing.JMenu mbarFile;
    private javax.swing.JMenuItem mniLogOut;
    private javax.swing.JMenuItem mniMenuAdmin;
    private javax.swing.JTextField txtIDCar;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
