/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.RentCar;

/**
 *
 * @author María Fernanda Murillo Alfaro
 * @author Karla Vanessa Ballestero Castro
 * @date 09/12/2017
 * 
 */
public class FrmMenuCustomer extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuCustomer
     */
    public FrmMenuCustomer() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void FrmRentCarCustomer(){
        FrmRentCarCustomer rent = new FrmRentCarCustomer();
        rent.setVisible(true);
        rent.setLocationRelativeTo(null);
        
    }
    public void FrmSearchVehicle(){
        FrmSearchVehicle search = new FrmSearchVehicle();
        search.setVisible(true);
        search.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRentCar = new javax.swing.JButton();
        btnSearchVehicle = new javax.swing.JButton();
        Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRentCar.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        btnRentCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/car (1).png"))); // NOI18N
        btnRentCar.setText("RentCar");
        btnRentCar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/car.png"))); // NOI18N
        btnRentCar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/car.png"))); // NOI18N
        btnRentCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentCarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRentCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 290, 110));

        btnSearchVehicle.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        btnSearchVehicle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/auto.png"))); // NOI18N
        btnSearchVehicle.setText("Search Vehicle");
        btnSearchVehicle.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/auto (1).png"))); // NOI18N
        btnSearchVehicle.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/auto.png"))); // NOI18N
        btnSearchVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchVehicleActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 290, 110));

        Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/Wallpaper_Second.jpg"))); // NOI18N
        getContentPane().add(Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRentCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentCarActionPerformed
      FrmRentCarCustomer();
    }//GEN-LAST:event_btnRentCarActionPerformed

    private void btnSearchVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchVehicleActionPerformed
      FrmSearchVehicle();
    }//GEN-LAST:event_btnSearchVehicleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Wallpaper;
    private javax.swing.JButton btnRentCar;
    private javax.swing.JButton btnSearchVehicle;
    // End of variables declaration//GEN-END:variables
}
