/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.RentCar;

import javax.swing.JOptionPane;

/**
 *
 * @author María Fernanda Murillo Alfaro
 * @author Karla Vanessa Ballestero Castro
 * @date 29/11/2017
 *
 */
public class FrmMenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuAdmin
     */
    public FrmMenuAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBrand = new javax.swing.JButton();
        btnCar = new javax.swing.JButton();
        btnModel = new javax.swing.JButton();
        btnOffice = new javax.swing.JButton();
        btnStyle = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBrand.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        btnBrand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/volante (1).png"))); // NOI18N
        btnBrand.setText("Brand");
        btnBrand.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/volante.png"))); // NOI18N
        btnBrand.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/volante.png"))); // NOI18N
        btnBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrandActionPerformed(evt);
            }
        });
        getContentPane().add(btnBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 150, 70));

        btnCar.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        btnCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/descapotable (1).png"))); // NOI18N
        btnCar.setText("Car");
        btnCar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/descapotable.png"))); // NOI18N
        btnCar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/descapotable.png"))); // NOI18N
        btnCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 150, 70));

        btnModel.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        btnModel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/modelo-de-coche-antiguo.png"))); // NOI18N
        btnModel.setText("Model");
        btnModel.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/coche-modelo-hatchback.png"))); // NOI18N
        btnModel.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/coche-redondeado-de-viejo-modelo.png"))); // NOI18N
        btnModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModelActionPerformed(evt);
            }
        });
        getContentPane().add(btnModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 150, 70));

        btnOffice.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        btnOffice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/carpeta.png"))); // NOI18N
        btnOffice.setText("Office");
        btnOffice.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/carpeta (1).png"))); // NOI18N
        btnOffice.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/carpeta (1).png"))); // NOI18N
        btnOffice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfficeActionPerformed(evt);
            }
        });
        getContentPane().add(btnOffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 190, 42));

        btnStyle.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        btnStyle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/coche-modelo-hatchback.png"))); // NOI18N
        btnStyle.setText("Style");
        btnStyle.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/descapotable (1).png"))); // NOI18N
        btnStyle.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/descapotable (1).png"))); // NOI18N
        btnStyle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStyleActionPerformed(evt);
            }
        });
        getContentPane().add(btnStyle, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 150, 70));

        btnExit.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/salida (1).png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/salida.png"))); // NOI18N
        btnExit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/salida.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 118, 42));

        lblWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/Wallpaper_Second.jpg"))); // NOI18N
        getContentPane().add(lblWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandActionPerformed
        goCrudBrand();
    }//GEN-LAST:event_btnBrandActionPerformed

    private void btnCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarActionPerformed
        goCrudCar();
    }//GEN-LAST:event_btnCarActionPerformed

    private void btnModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModelActionPerformed
        goCrudModel();
    }//GEN-LAST:event_btnModelActionPerformed

    private void btnOfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfficeActionPerformed
        goCrudOffice();
    }//GEN-LAST:event_btnOfficeActionPerformed

    private void btnStyleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStyleActionPerformed
        goCrudStyle();
    }//GEN-LAST:event_btnStyleActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        LogOut();
    }//GEN-LAST:event_btnExitActionPerformed

    
    //Method to go to the crud brand
    private void goCrudBrand() {
        FrmCRUDBrand brand = new FrmCRUDBrand();
        brand.setVisible(true);
        brand.setLocationRelativeTo(null);
        dispose();
    }
    
    //Method to go to the crud car
    private void goCrudCar() {
        FrmCRUDCar car = new FrmCRUDCar();
        car.setVisible(true);
        car.setLocationRelativeTo(null);
        dispose();
    }
    
    //Method to go to the crud model
    private void goCrudModel() {
        FrmCRUDModel model = new FrmCRUDModel();
        model.setVisible(true);
        model.setLocationRelativeTo(null);
        dispose();
    }    
    
    //Method to go to the crud office
    private void goCrudOffice() {
        FrmCRUDOffice office = new FrmCRUDOffice();
        office.setVisible(true);
        office.setLocationRelativeTo(null);
        dispose();
    }
    
    //Method to go to the crud style
    private void goCrudStyle() {
        FrmCRUDStyle style = new FrmCRUDStyle();
        style.setVisible(true);
        style.setLocationRelativeTo(null);
        dispose();
    }
    
    //Method to close session
    private void LogOut() {
        JOptionPane.showMessageDialog(null, "Finalized session");
        FrmLogin out = new FrmLogin();
        out.setVisible(true);
        dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrand;
    private javax.swing.JButton btnCar;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnModel;
    private javax.swing.JButton btnOffice;
    private javax.swing.JButton btnStyle;
    private javax.swing.JLabel lblWallpaper;
    // End of variables declaration//GEN-END:variables
}
