/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.RentCar;

import java.util.Date;
import java.util.Calendar;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author ACER
 */
public class FrmRentCarCustomer extends javax.swing.JFrame {

    /**
     * Creates new form FrmRentCarCustomer
     */
    public FrmRentCarCustomer() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
   
  


           
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSelctVehicle = new javax.swing.JLabel();
        lblSelectDate = new javax.swing.JLabel();
        lblSelectOffice = new javax.swing.JLabel();
        lblSelectTime2 = new javax.swing.JLabel();
        lblIndicate2 = new javax.swing.JLabel();
        lblIndicate = new javax.swing.JLabel();
        lblSelectDate2 = new javax.swing.JLabel();
        lblAdditionalItems = new javax.swing.JLabel();
        txtOffice = new javax.swing.JTextField();
        txtSelectVehicle = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        Date date = new Date();
        SpinnerDateModel sm =
        new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);
        jSpinner1 = new javax.swing.JSpinner(sm);
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSelctVehicle.setBackground(new java.awt.Color(255, 255, 255));
        lblSelctVehicle.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lblSelctVehicle.setForeground(new java.awt.Color(255, 255, 255));
        lblSelctVehicle.setText(" Select Vehicle:");
        getContentPane().add(lblSelctVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 110, 30));

        lblSelectDate.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lblSelectDate.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectDate.setText("Select Date and Time:");
        getContentPane().add(lblSelectDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 160, 30));

        lblSelectOffice.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lblSelectOffice.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectOffice.setText("Select Office:");
        getContentPane().add(lblSelectOffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 90, 30));

        lblSelectTime2.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lblSelectTime2.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectTime2.setText("Select Time:");
        getContentPane().add(lblSelectTime2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 90, 20));

        lblIndicate2.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        lblIndicate2.setForeground(new java.awt.Color(255, 255, 51));
        lblIndicate2.setText("Please  Indicate  date and time of return of the vehicle");
        getContentPane().add(lblIndicate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 340, -1));

        lblIndicate.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        lblIndicate.setForeground(new java.awt.Color(255, 255, 51));
        lblIndicate.setText("Please Indicate where, date and time of vehicle removal");
        getContentPane().add(lblIndicate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 320, -1));

        lblSelectDate2.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lblSelectDate2.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectDate2.setText("Select Date:");
        getContentPane().add(lblSelectDate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 80, 30));

        lblAdditionalItems.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lblAdditionalItems.setForeground(new java.awt.Color(255, 255, 255));
        lblAdditionalItems.setText("Additional items:");
        getContentPane().add(lblAdditionalItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 120, 20));
        getContentPane().add(txtOffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 150, 30));

        txtSelectVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSelectVehicleActionPerformed(evt);
            }
        });
        getContentPane().add(txtSelectVehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 150, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/right-tick (1).png"))); // NOI18N
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/right-tick.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/right-tick.png"))); // NOI18N
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 60, 50));

        lblTotal.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total :");
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 50, 30));

        JSpinner.DateEditor de = new JSpinner.DateEditor(jSpinner1, ("dd/MM/yyyy HH:mm:ss"));
        jSpinner1.setEditor(de);
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 230, 30));

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        jTextField2.setText("jTextField2");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/Wallpaper_Second.jpg"))); // NOI18N
        getContentPane().add(Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSelectVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSelectVehicleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSelectVehicleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRentCarCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRentCarCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRentCarCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRentCarCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRentCarCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Wallpaper;
    private javax.swing.JButton jButton1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblAdditionalItems;
    private javax.swing.JLabel lblIndicate;
    private javax.swing.JLabel lblIndicate2;
    private javax.swing.JLabel lblSelctVehicle;
    private javax.swing.JLabel lblSelectDate;
    private javax.swing.JLabel lblSelectDate2;
    private javax.swing.JLabel lblSelectOffice;
    private javax.swing.JLabel lblSelectTime2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtOffice;
    private javax.swing.JTextField txtSelectVehicle;
    // End of variables declaration//GEN-END:variables
}
