/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.RentCar;

import BO.RentCar.CustomerBO;
import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import Logic.RentCar.Customer;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author María Fernanda Murillo Alfaro
 * @author Karla Vanessa Ballestero Castro
 * @date 19/11/2017
 *
 */
public class FrmSignIn extends javax.swing.JFrame {

    private LinkedList<Customer> customerList;
    private File file;
    private String photo;

    /**
     * Creates new form FrmSignIn
     */
    public FrmSignIn() {
        initComponents();
        this.setLocationRelativeTo(null);
        customerList = new LinkedList<>();
    }

    public FrmSignIn(LinkedList<Customer> customerList) {
        this.customerList = customerList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblLastname = new javax.swing.JLabel();
        lblTelephone = new javax.swing.JLabel();
        lblDirection = new javax.swing.JLabel();
        lblPassword1 = new javax.swing.JLabel();
        lblPassword2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        txtTelephone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDirection = new javax.swing.JTextArea();
        password1 = new javax.swing.JPasswordField();
        password2 = new javax.swing.JPasswordField();
        lblPhoto = new javax.swing.JLabel();
        btnSelectPhoto = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        lblRegister = new javax.swing.JLabel();
        lblWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setText("ID:");
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 112, -1, -1));

        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name:");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        lblLastname.setForeground(new java.awt.Color(255, 255, 255));
        lblLastname.setText("Lastname:");
        getContentPane().add(lblLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        lblTelephone.setForeground(new java.awt.Color(255, 255, 255));
        lblTelephone.setText("Telephone:");
        getContentPane().add(lblTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        lblDirection.setForeground(new java.awt.Color(255, 255, 255));
        lblDirection.setText("Direction:");
        getContentPane().add(lblDirection, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        lblPassword1.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword1.setText("Password:");
        getContentPane().add(lblPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        lblPassword2.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword2.setText("Password:");
        getContentPane().add(lblPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        txtID.setBackground(new java.awt.Color(51, 51, 51));
        txtID.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 110, -1));

        txtName.setBackground(new java.awt.Color(51, 51, 51));
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 120, -1));

        txtLastname.setBackground(new java.awt.Color(51, 51, 51));
        txtLastname.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 120, -1));

        txtTelephone.setBackground(new java.awt.Color(51, 51, 51));
        txtTelephone.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 120, -1));

        txaDirection.setBackground(new java.awt.Color(51, 51, 51));
        txaDirection.setColumns(20);
        txaDirection.setForeground(new java.awt.Color(255, 255, 255));
        txaDirection.setRows(5);
        jScrollPane1.setViewportView(txaDirection);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        password1.setBackground(new java.awt.Color(51, 51, 51));
        password1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 136, -1));

        password2.setBackground(new java.awt.Color(51, 51, 51));
        password2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 136, -1));
        getContentPane().add(lblPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 43, 144, 154));

        btnSelectPhoto.setBackground(new java.awt.Color(0, 0, 51));
        btnSelectPhoto.setForeground(new java.awt.Color(255, 255, 255));
        btnSelectPhoto.setText("Select a photo");
        btnSelectPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectPhotoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, -1, -1));

        btnRegister.setBackground(new java.awt.Color(0, 0, 51));
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 584, -1, -1));

        lblRegister.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblRegister.setForeground(new java.awt.Color(255, 255, 255));
        lblRegister.setText("REGISTER");
        getContentPane().add(lblRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        lblWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RentCar/wallpaper.jpg"))); // NOI18N
        getContentPane().add(lblWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Method for find a photo
    private void findPhoto() {
        int result;
        FrmPhoto frm = new FrmPhoto();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG and PNG", "jpg", "png");
        frm.jfchPhoto.setFileFilter(filter);
        result = frm.jfchPhoto.showOpenDialog(null);
        if (JFileChooser.APPROVE_OPTION == result) {
            file = frm.jfchPhoto.getSelectedFile();
            try {
                ImageIcon icon = new ImageIcon(file.toString());
                photo = file.toString();
                Icon picture = new ImageIcon(icon.getImage().getScaledInstance(lblPhoto.getWidth(), lblPhoto.getHeight(), Image.SCALE_DEFAULT));
                lblPhoto.setText("");
                lblPhoto.setIcon(picture);
            } catch (Exception ex) {
                System.out.println("Error opening the image" + ex);
            }
        }
    }

    //Method to register
    private void registerNewCustomer() {
        try {
            CustomerBO cbo = new CustomerBO();
            Customer c = new Customer();
            c.setId_customer(Integer.parseInt(txtID.getText()));
            c.setName(txtName.getText());
            c.setLastname(txtLastname.getText());
            c.setTelephone(Integer.parseInt(txtTelephone.getText()));
            c.setDirection(txaDirection.getText());
            c.setPhoto(photo);

            if (password1.getText().equals(password2.getText())) {
                c.setPassword(password1.getText());

                if (cbo.register(c)) {
                    JOptionPane.showMessageDialog(null, "Registered");
                }
                System.out.println(c.getName() + " " + c.getLastname());

                goLogin();

            } else {
                JOptionPane.showMessageDialog(null, "Passwords do not match");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    //Method to go to the login
    private void goLogin() {
        FrmLogin login = new FrmLogin();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        dispose();
    }


    private void btnSelectPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectPhotoActionPerformed
        findPhoto();
    }//GEN-LAST:event_btnSelectPhotoActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        registerNewCustomer();
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSelectPhoto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDirection;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JLabel lblPassword2;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblTelephone;
    private javax.swing.JLabel lblWallpaper;
    private javax.swing.JPasswordField password1;
    private javax.swing.JPasswordField password2;
    private javax.swing.JTextArea txaDirection;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTelephone;
    // End of variables declaration//GEN-END:variables
}
